// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BLL.DAL;

public partial class City
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(125)]
    public string Name { get; set; }

    public int CountryId { get; set; }

    [ForeignKey("CountryId")]
    [InverseProperty("Cities")]
    public virtual Country Country { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<Store> Stores { get; set; } = new List<Store>();
}